src/gallery/urls.py
from django.urls import path
from gallery import views


app_name = 'gallery'
urlpatterns = [
    path('', views.PetList.as_view(), name='home'),
    path('create/', views.PetCreate.as_view(), name='pet-create'),
    path('<int:pk>/', views.PetDetail.as_view(), name='pet-detail'),
]

src/main/urls.py
from django.urls import path, re_path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    re_path(r'^favicon\.ico$', views.Favicon.as_view())
]

src/gallery/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


class Pet(models.Model):

    PETS_CH = [(p, p.title()) for p in [
        'cat', 'dog', 'goldfish', 'hamster', 'mouse',
        'parrot', 'rabbit', 'turtle'
    ]]
    GENDERS_CH = [(g, g.title()) for g in [
        'male', 'female'
    ]]

    name = models.CharField(max_length=20)
    category = models.CharField(max_length=10, choices=PETS_CH)
    breed = models.CharField(max_length=30, blank=True)
    gender = models.CharField(max_length=8, choices=GENDERS_CH)
    age = models.SmallIntegerField()
    description = models.CharField(max_length=150)
    uploaded = models.DateTimeField(auto_now_add=True)

    @property
    def get_absolute_url(self):
        return reverse('gallery:pet-detail', args=(self.pk,))

    def __str__(self):
        return self.name


class PetPhoto(models.Model):

    image = models.ImageField(upload_to='pets_photos', blank=True)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)

src/gallery/forms.py
from django.forms.models import inlineformset_factory
from django.template.loader import render_to_string
from django.forms import ValidationError
from django.template import Template
from re import sub

from crispy_forms.helper import FormHelper
from crispy_forms.layout import LayoutObject, ButtonHolder, Submit, HTML
from crispy_forms.layout import Layout, Row, Column, Fieldset, Div, Field

from django import forms
from gallery import models


class SucessField(Field):
    template = 'forms/success_field.html'


class JasnyImageField(LayoutObject):

    def __init__(self, name, prefix):
        self.template = 'forms/image_field.html'
        self.name = name
        self.prefix = prefix

    def render(self, form, form_style, context, template_pack):
        extra_context = {
            'field_name': self.name,
            'field_prefix': self.prefix
        }
        return render_to_string(self.template, extra_context)


class SubmitOutline(Submit):
    def __init__(self, *args, **kwargs):
        super(SubmitOutline, self).__init__(*args, **kwargs)
        self.field_classes = 'col col-md-4 btn btn-outline-success ml-md-auto'


class Formset(LayoutObject):

    def __init__(self, formset_name):
        self.template = 'forms/formset.html'
        self.formset_name = formset_name

    def render(self, form, form_style, context, **kwargs):
        extra_context = {
            'formset': context[self.formset_name]
        }
        return render_to_string(self.template, extra_context)


class Control:

    def __init__(self, direction, css_classes):
        control_base = '<span class=\"{}\">\n\t' + \
                       '<i class=\"fas fa-angle-{}\"></i>\n' + \
                       '</span>'
        self.html = control_base.format(css_classes, direction)

    def render(self, form, form_style, context, **kwargs):
        return Template(str(self.html)).render(context)


class PetPhotoForm(forms.ModelForm):

    class Meta:
        model = models.PetPhoto
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(PetPhotoForm, self).__init__(*args, **kwargs)

        formtag_prefix = sub('-[0-9]+$', '', kwargs.get('prefix', ''))

        self.helper = FormHelper()
        self.helper.disable_csrf = True

        self.helper.layout = Layout(
            Row(
                JasnyImageField('image', kwargs.get('prefix', '')),
                css_class='formset_row-{}'.format(formtag_prefix)
            )
        )

    def clean(self):
        cleaned_data = super().clean()
        return cleaned_data

class PetForm(forms.ModelForm):

    class Meta:
        model = models.Pet
        exclude = ['created_by']

        widgets = {
            'description': forms.Textarea(attrs={'cols': 70, 'rows': 4})
        }
        help_texts = {
            'age': 'Type it in years',
            'description': '150 symbols'
        }

    def __init__(self, *args, **kwargs):
        super(PetForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.disable_csrf = True

        self.helper.layout = Layout(Div(
            Row(
                Column(SucessField('name'), css_class='col-12'),
                Column(SucessField('category'), css_class='col-12 col-sm-6'),
                Column(SucessField('breed'), css_class='col-12 col-sm-6'),
                Column(SucessField('gender'), css_class='col-12 col-sm-6'),
                Column(SucessField('age'), css_class='col-12 col-sm-6'),
                Column(SucessField('description'), css_class='col-12')
            ),
            Fieldset(
                'Add photo',
                Div(
                    Formset('photo'),
                    css_class='formset-photos'
                ),
                Control('left', 'formset-prev d-none d-sm-flex'),
                Control('right', 'formset-next d-none d-sm-flex'),
                css_class='form-row-photos'
            ),
            HTML('<hr>'),
            ButtonHolder(
                SubmitOutline('submit', 'Create', formnovalidate=''),
                css_class='d-flex'
            )
        ))

    def clean(self):
        cleaned_data = super().clean()
        age = cleaned_data.get('age')

        if age and (age < 0 or age > 100):
            raise ValidationError(
                {'age': 'Incorrect age. Please, write it again.'}
            )

        return cleaned_data

PetFormset = inlineformset_factory(
    models.Pet,
    models.PetPhoto,
    form=PetPhotoForm,
    fields=['image'],
    extra=0,
    can_delete=True,
    min_num=1,
    max_num=6
)

src/gallery/views.py
from django.http.response import HttpResponseNotFound, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView
from django.db import transaction
from django.db.models import Q

from gallery import models
from gallery import forms

class PetList(ListView):
    model = models.Pet
    extra_context = {'page_title': 'animals'}
    ordering = '-id'
    paginate_by = 6

    def get(self, request, *args, **kwargs):
        sort_by = request.GET.get('sort')
        if sort_by:
            self.object_list = models.Pet.objects.all().order_by(
                '-' + sort_by
            )
            self.paginate_by = None
            context = self.get_context_data()
            context['sorted_by'] = sort_by
            return self.render_to_response(context)

        search_query = request.GET.get('search')
        if search_query:
            self.object_list = models.Pet.objects.filter(
                Q(name__icontains=search_query) |
                Q(description__icontains=search_query) |
                Q(gender__icontains=search_query) |
                Q(category__icontains=search_query)
            ).order_by(self.ordering)
            self.paginate_by = None
            context = self.get_context_data()
            context['search_query'] = search_query
            return self.render_to_response(context)

        return super().get(self, request, *args, **kwargs)


class PetDetail(DetailView):
    model = models.Pet
    extra_context = {'page_title': 'animals'}

    def get(self, request, *args, **kwargs):
        self.extra_context['last_page'] = request.META.get(
            'HTTP_REFERER', reverse('gallery:home')
        )
        if '/create/' in self.extra_context['last_page']:
            self.extra_context['last_page'] = reverse('gallery:home')

        return super().get(request, *args, **kwargs)


class PetCreate(CreateView):
    model = models.Pet
    form_class = forms.PetForm
    extra_context = {
        'page_title': 'animals',
        'navbar_title': 'creating application'
    }

    def get(self, request, *args, **kwargs):
        self.extra_context['last_page'] = request.META.get(
            'HTTP_REFERER', reverse('gallery:home')
        )
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = None
        form = self.get_form()
        print(request.POST, request.FILES, sep='\n')
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data['photo'] = forms.PetFormset(
                self.request.POST, self.request.FILES
            )
        else:
            data['photo'] = forms.PetFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        photos = context.get('photo')

        with transaction.atomic():
            form.instance.created_by = self.request.user
            if not photos.is_valid():
                return self.form_invalid(form)
            self.object = form.save()
            photos.instance = self.object
            photos.save()

        return HttpResponseRedirect(
            reverse_lazy('gallery:pet-detail', args=(self.object.pk,))
        )

src/gallery/templates/gallery/base.html
{% extends 'index.html' %}

{% block content %}

<div class="container-fluid category-fluid">
    <div class="container py-4 py-md-5">
        {% block gallery_content %}
        {% endblock %}
    </div>
</div>

{% endblock %}

src/gallery/templates/gallery/pet_detail.html
{% extends 'gallery/base.html' %}
{% load staticfiles %}

{% block extra_links %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.10.0/css/lightgallery.min.css" integrity="sha512-gk6oCFFexhboh5r/6fov3zqTCA2plJ+uIoUx941tQSFg6TNYahuvh1esZVV0kkK+i5Kl74jPmNJTTaHAovWIhw==" crossorigin="anonymous" />
{% endblock %}

{% block title %}
    {{ object.name|title }}
{% endblock %}

{% block gallery_content %}

<a class="btn btn-light back-link" href="{{ last_page }}">
    <i class="fas fa-chevron-left ml-1"></i>
    <span>Back</span>
</a>

<div class="card text-white bg-dark pet-detail mt-4">
    <div class="card-header">Pet detail</div>
    <div class="card-body row justify-content-center">
        {% if object.petphoto_set.first %}
            <div class="col-12 col-md-7 card-body-photo row">
                <a class="col-12 p-1" href="{{ object.petphoto_set.first.image.url }}">
                    <div
                        class="card-body-photo-first"
                        style="background-image: url({{ object.petphoto_set.first.image.url }})"
                    ></div>
                </a>
                {% for photo in object.petphoto_set.all %}
                {% if forloop.counter != 1 %}
                    <a class="col p-1 pt-2" href="{{ photo.image.url }}">
                        <div
                            class="card-body-photo-other"
                            style="background-image: url({{ photo.image.url }})"
                        ></div>
                    </a>
                {% endif %}
                {% endfor %}
            </div>
        {% else %}
            <div class="col-12 col-md-7 row">
                <div class="card-body-photo-empty">
                    <span class="text-center">
                        There is no photo uploaded yet
                        <i class="far fa-frown"></i>
                    </span>
                </div>
            </div>
        {% endif %}
        <div class="col-12 col-md-5 mt-4 mt-md-2 ml-0 ml-md-3">
            <h5 class="card-title">{{ object.name }}</h5>
            <p class="card-text">{{ object.description }}</p>
            <hr>
            <p class="card-text">
                {{ object.category|title }}{% if object.breed %}, {{ object.breed|title }}{% endif %}
            </p>
            <hr>
            <p class="card-text">
                <span class="undeline">Gender:</span>
                <span>{{ object.gender|title }}</span>
            </p>
            <hr>
            <p class="card-text">
                <span class="undeline">Age:</span>
                <span>{{ object.age }} years</span>
            </p>
            <hr>
            <p class="card-text">
                <span class="undeline">On site from:</span>
                <span>{{ object.uploaded|date:"M m, H:i" }}</span>
            </p>
            <hr>
        </div>
    </div>
</div>

{% endblock %}

{% block extra_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightgallery/1.10.0/js/lightgallery-all.min.js" integrity="sha512-Qpvw3WG46QyOqV/YS9BosbxEbMKPREA+QS+iWAKXfvb/87tdfsGGQdT7vqYbQzBOgLvF2I/MHMacA86oURHsCw==" crossorigin="anonymous"></script>
    <script src="{% static 'js/pet_detail.js' %}"></script>
{% endblock %}

src/gallery/templates/gallery/pet_form.html
{% extends 'gallery/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block extra_links %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/4.0.0/css/jasny-bootstrap.min.css">
{% endblock %}

{% block gallery_content %}

    <a class="btn btn-light back-link" href="{{ last_page }}">
        <i class="fas fa-chevron-left ml-1"></i>
        <span>Back</span>
    </a>

    <form
        class="pet-create"
        action="{% url 'gallery:pet-create' %}"
        method="post"
        enctype="multipart/form-data"
    >
        {% csrf_token %}
        {% crispy form %}
    </form>

{% endblock %}

{% block extra_scripts %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jasny-bootstrap/4.0.0/js/jasny-bootstrap.min.js"></script>
    <script src="{% static 'js/pet_form.js' %}"></script>
{% endblock %}

src/gallery/templates/gallery/pet_list.html
{% extends 'gallery/base.html' %}
{% load staticfiles %}

{% block gallery_content%}

<div class="pet-list">
    <div class="row align-items-center">
        <div class="col-sm-6 col-md-8 d-none d-sm-block">
            <span class="display-4">Animals</span>
        </div>
        <div class="col-12 col-sm-6 col-md-4">
            <a class="btn btn-dark btn-create" href="{% url 'gallery:pet-create' %}">
                Create an application
            </a>
        </div>
    </div>
    <hr>
    <div class="row">
        <form class="form-inline form-search w-100">
            <div class="col-12 col-md-6 col-lg-8">
                <input class="form-control w-100" type="search" name="search" placeholder="What're we lookng for?">
            </div>
            <div class="col-12 col-md-6 col-lg-4 mt-3 mt-md-0 btn-group">
                <button type="submit" class="btn btn-light">Search</button>
                <div class="divider"></div>
                <button class="btn btn-light dropdown-toggle dropdown-toggle-split" data-toggle="dropdown">
                    <span>Sort by</span><span class="sr-only"></span>
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <button type="submit" name="sort" value="category" class="dropdown-item">
                        Category
                    </button>
                    <button type="submit" name="sort" value="age" class="dropdown-item">
                        Pet age
                    </button>
                    <div class="dropdown-divider"></div>
                    <button type="submit" name="sort" value="uploaded" class="dropdown-item">
                        Latest uploaded
                    </button>
                </div>
            </div>
        </form>
    </div>
    {% if search_query or sorted_by %}
        <div class="row mt-3">
            <div class="col-12 ml-1">
                <span style="color: #3e3ed9;">
                    {% if search_query %}
                        {% if search_query|length > 15 %}
                            Results of searching «{{ search_query|slice:15|add:'...' }}»
                        {% else %}
                            Results of searching «{{ search_query}}»
                        {% endif %}
                    {% else %}
                        Sorted by «{{ sorted_by }}»
                    {% endif %}
                </span>
                <a style="color: #cf2d2d;" href="{% url 'gallery:home' %}">
                    <i class="fas fa-times"></i>
                </a>
            </div>
        </div>
    {% endif %}
    <hr>
    <div class="row">
    {% for pet in object_list %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card my-3">
            {% if pet.petphoto_set.all|length > 1 %}
                <div
                    id="carouselControls-{{ forloop.counter }}"
                    class="card-img-top carousel slide" data-ride="carousel"
                >
                    <div class="carousel-inner">
                        {% for photo in pet.petphoto_set.all %}
                            <div
                                class="carousel-item card-img-top {% if forloop.counter == 1 %}active{% endif %}"
                                style="background-image: url({{ photo.image.url }})"
                            ></div>
                        {% endfor %}
                    </div>
                    <a
                        class="carousel-control-prev" data-slide="prev"
                        href="#carouselControls-{{ forloop.counter }}"
                    >
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a
                        class="carousel-control-next" data-slide="next"
                        href="#carouselControls-{{ forloop.counter }}"
                    >
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            {% elif pet.petphoto_set.all|length == 1 %}
                <div
                    class="card-img-top"
                    style="background-image: url({{ pet.petphoto_set.first.image.url }})"
                ></div>
            {% else %}
                <div
                    class="card-img-top"
                    style="background-color: #666"
                ></div>
            {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ pet.name }}</h5>
                    <p class="card-text">{{ pet.description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">
                        {{ pet.category|title }},
                        {{ pet.gender|title }}
                    </li>
                    <li class="list-group-item">
                        {{ pet.age }} years
                    </li>
                </ul>
                <div class="card-body">
                    <a href="{{ pet.get_absolute_url }}" class="card-link">
                        <button class="btn btn-light w-100" title="Show pet page">
                            Open
                        </button>
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
    {% if page_obj.has_other_pages %}
    <div class="row">
        <nav class="col-12 mt-4">
            <ul class="pagination justify-content-center">
                <li class="page-item {% if not page_obj.has_previous %}disabled{% endif %}">
                    {% if page_obj.has_previous %}
                        <a class="page-link btn" href="?page={{ page_obj.previous_page_number }}">
                            Previous
                        </a>
                    {% else %}
                        <a class="page-link btn ml-1" href="">Previous</a>
                    {% endif %}
                </li>

                {% for n in page_obj.paginator.page_range %}
                    {% if page_obj.number == n %}
                        <li class="page-item active">
                            <a class="page-link btn ml-1" href="?page={{ n }}">{{ n }}</a>
                        </li>
                    {% elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
                        <li class="page-item">
                            <a class="page-link btn ml-1" href="?page={{ n }}">{{ n }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                <li class="page-item {% if not page_obj.has_next %}disabled{% endif %}">
                    {% if page_obj.has_next %}
                        <a class="page-link btn ml-1" href="?page={{ page_obj.next_page_number }}">
                            Next
                        </a>
                    {% else %}
                        <a class="page-link btn ml-1" href="">Next</a>
                    {% endif %}
                </li>
          </ul>
        </nav>
    </div>
    {% endif %}
</div>

{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'js/pet_list.js' %}"></script>
{% endblock %}