src/gallery/urls.py
from django.urls import path
from gallery import views


app_name = 'gallery'
urlpatterns = [
    path('', views.PetList.as_view(), name='home'),
    path('create/', views.PetCreate.as_view(), name='pet-create'),
    path('<int:pk>/', views.PetDetail.as_view(), name='pet-detail'),
]

src/main/urls.py
from django.urls import path, re_path
from main import views

app_name = 'main'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name='about'),
    re_path(r'^favicon\.ico$', views.Favicon.as_view())
]

src/main/views.py
from django.views.generic import TemplateView, RedirectView
from django.shortcuts import render


class Home(TemplateView):
    template_name = 'index.html'
    extra_context = {
        'page_title': 'home',
        'navbar_title': ''
    }


class About(TemplateView):
    template_name = 'about.html'
    extra_context = {'page_title': 'about'}


class Favicon(RedirectView):
    url = '/static/img/icons/favicon.svg'
    permanent = True


def handler404(request, *args, **kwargs):
    context = {'page_title': '404 error'}
    return render(request, '404.html', context, status=404)


def handler500(request, *args, **kwargs):
    context = {'page_title': '500 error'}
    return render(request, '500.html', context, status=500)

src/main/templates/index.html
<!DOCTYPE html>

{% load staticfiles %}
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    {#  Bootstrap, Jasny Bootstrap & Google Fonts  #}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@200;400;600;700&display=swap">
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">

    {% block extra_links %}{% endblock %}

    <title>{% block title %}{{ page_title|title }}{% endblock %}</title>
</head>

<body class="position-relative">

    {% block header %}

    <div class="sidemenu">
    <div class="sidemenu-wrapper">
        <nav class="nav">
            <a class="nav__item" onclick="location.href='{% url 'main:home' %}'">
                <span class="nav__link">
                    Home
                </span>
            </a>
            <a class="nav__item" onclick="location.href='{% url 'gallery:home' %}'">
                <span class="nav__link">
                    Animals
                </span>
            </a>
            <a class="nav__item" onclick="location.href='{% url 'main:about' %}'">
                <span class="nav__link">
                    About
                </span>
            </a>
        </nav>
        <div class="preview-box">
            <div style="background-image: url({% static 'img/header_home.jpg' %})">
                <span>HOME</span>
            </div>
            <div style="background-image: url({% static 'img/header_gallery.jpg' %})">
                <span>ANIMALS</span>
            </div>
            <div style="background-image: url({% static 'img/header_about.jpg' %})">
                <span>ABOUT</span>
            </div>
        </div>
    </div>
    </div>

    <header class="navbar navbar-dark bg-dark fixed-top">
        <button class="navbar-toggler">
            <div class="navbar-button d-flex align-items-center">
              <div class="navbar-button-burger"></div>
            </div>
        </button>
        <span class="navbar-brand title-lg m-0 p-0">
            {% if navbar_title %}
                {{ navbar_title|title }}
            {% else %}
                {{ page_title|title }}
            {% endif %}
        </span>
        <span class="navbar-brand title-xs m-0 p-0">
            {% if navbar_title %}
                {% if navbar_title|length > 12 %}
                    {{ navbar_title|slice:12|add:'.'|title }}
                {% else %}
                    {{ navbar_title|title }}
                {% endif %}
            {% else %}
                {{ page_title|title }}
            {% endif %}
        </span>
    </header>

    {% endblock %}

    {% block content %}
    <div
        class="container-fluid main-fluid"
        style="background-image: url({% static 'img/home_bg.jpg' %})"
    >
        <div class="jumbotron mt-3 mt-md-5">
          <h1 class="display-4">
              <i class="fas fa-paw mr-1"></i>
              <span>Animal shelter</span>
          </h1>
          <p class="lead mt-2">
              Welcome on website of our animal shelter, here you can
              find pets that are looking for their owners! </p>
          <hr class="my-4">
          <p>Photos and other information you can find in the section Animals</p>
          <p class="lead">
            <a class="btn btn-light btn-lg mt-3" href="{% url 'gallery:home' %}">
                <span>Go find a pet</span>
                <i class="fas fa-dog ml-2"></i>
            </a>
          </p>
        </div>
    </div>
    {% endblock %}

    {#  jQuery, Popper.js, Bootstrap, Anime.js & FontAwesome  #}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js" integrity="sha512-z4OUqw38qNLpn1libAN9BsoDx6nbNFio5lA6CuTp9NlK83b89hgyCVq+N5FdBJptINztxn1Z3SaKSKUS5UP60Q==" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/04a7c4bbdc.js" crossorigin="anonymous"></script>
    <script src="{% static 'js/main.js' %}"></script>

    {% block extra_scripts %}{% endblock %}
</body>
</html>